# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f7444bc7ce7f32684e08445602e9fcb9"
application_url = "https://altered-yen-nice-triangle.trycloudflare.com"
embedded = true
name = "boa-home-task-SKH"
handle = "boa-home-task-skh"

[build]
include_config_on_deploy = true
dev_store_url = "home-assignment-240.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://altered-yen-nice-triangle.trycloudflare.com/auth/callback",
  "https://altered-yen-nice-triangle.trycloudflare.com/auth/shopify/callback",
  "https://altered-yen-nice-triangle.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
