# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "de72ddb7011065720a6f3f546b230694"
application_url = "https://host-totals-fm-removing.trycloudflare.com"
embedded = true
name = "boa-home-task-YK"
handle = "boa-home-task-yk"

[build]
include_config_on_deploy = true
dev_store_url = "home-assignment-261.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_products,read_products"

[auth]
redirect_urls = [
  "https://host-totals-fm-removing.trycloudflare.com/auth/callback",
  "https://host-totals-fm-removing.trycloudflare.com/auth/shopify/callback",
  "https://host-totals-fm-removing.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[app_proxy]
url = "https://host-totals-fm-removing.trycloudflare.com"
prefix = "apps"
subpath = "saved-cart"
