# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b4aa1ade8edf5ebaaeeb934ddc765940"
application_url = "https://overcome-angeles-turkish-ends.trycloudflare.com"
embedded = true
name = "boa-home-task-{SB}"
handle = "boa-home-task-sb"

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://overcome-angeles-turkish-ends.trycloudflare.com/auth/callback",
  "https://overcome-angeles-turkish-ends.trycloudflare.com/auth/shopify/callback",
  "https://overcome-angeles-turkish-ends.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://overcome-angeles-turkish-ends.trycloudflare.com"
subpath = "save-cart-proxy"
prefix = "apps"

[pos]
embedded = false

[build]
dev_store_url = "home-assignment-120.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
